# Generated by Django 5.0.7 on 2024-07-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='departamentos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('departamento', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='forma_pago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('f_pago', models.CharField(max_length=1000, verbose_name='Forma de Pago')),
            ],
            options={
                'verbose_name': 'Forma de pago',
                'verbose_name_plural': 'Formas de pago',
            },
        ),
        migrations.CreateModel(
            name='tipo_contrato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('t_contrato', models.CharField(max_length=1000, verbose_name='Tipo de Contrato')),
            ],
            options={
                'verbose_name': 'Tipo Contrato',
                'verbose_name_plural': 'Tipos de Contratos',
            },
        ),
    ]
