# Generated by Django 5.0.7 on 2024-07-18 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
        ('nomencladores', '0002_alter_tipo_contrato_t_contrato'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contratos',
            new_name='contrato',
        ),
    ]
